# Generated by Django 5.2.14 on 2026-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('code_type', models.IntegerField(choices=[(1, 'Login'), (2, 'Signup'), (3, 'Password Reset')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Verified'), (3, 'Expired'), (4, 'Failed')], default=1)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempt_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='createus_au_email_a2f1b7_idx'), models.Index(fields=['email', 'status'], name='createus_au_email_506e2d_idx')],
            },
        ),
    ]
